# Generated by Django 2.2.12 on 2021-04-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('telefon', models.IntegerField()),
                ('specjalnosc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('plec', models.CharField(max_length=10)),
                ('telefon', models.IntegerField(null=True)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spotkanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('czas', models.TimeField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szpital.Doktor')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szpital.Pacjent')),
            ],
        ),
    ]
